// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yhcfjnugzbiurdidazkk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InloY2ZqbnVnemJpdXJkaWRhemtrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjE1Nzc2OTEsImV4cCI6MjA3NzE1MzY5MX0.uhSZ46ATLUw6V1sykVOtdLVLN2vSo2LdTavZjEJpBlg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});